server:
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 20971520
  servlet:
    context-path: /htveh

spring:
  profiles:
    active: test
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/templates/
    order: 0
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      number_format: 0.##########
      datetime_format: yyyy-MM-dd HH:mm:ss
      classic_compatible: true
      template_exception_handler: ignore
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis.xml
